### ISSUE TITLE
Configurable time between update checks, or store last update time outside .gitconfig

### ISSUE THREAD

**Issue by agentydragon** [gabyx/Githooks#131]
Hi, I have my dotfiles including .gitconfig stored in a repository.

The githooks update mechanism stores the last time an autoupdate check was performed in .gitconfig, and checks every 24 hours.

This means that basically every time I go into my dotfiles repo, I'll see a spurious diff in the timestamp caused by githooks having executed an autoupdate check since my last commit.

Minor annoyance but it'd be nice to get it fixed.

I think .gitconfig isn't the best place for this, I think one better place for autoupdate time might be XDG_CACHE_DIR or something.

Or alternatively, another thing that would make the slight annoyance less annoying would be ability to set githooks to autoupdate on a longer interval than 24 hours - i.e. having an option for this interval rather than it being hardcoded in https://github.com/gabyx/Githooks/blob/f4cc437323cf685d8580a8a1d4c39fb0deebdc84/githooks/apps/runner/runner.go#L386

Thanks for your work on this, good piece of software!

**Comment by gabyx** [comment]
Hi, I also have that issue, that the gitconfig is changed due to this...

You are totally right. I guess its only the autoupdate time which is a problem, right.
So I could easily move that part out to the `~/.githooks/.last-update-time`. Would make also my dotfiles easier.
I might do that in while.

Thanks for the report.

**Comment by agentydragon** [comment]
thanks for the quick fix :)
